services:
  - type: web
    name: kanairoxo-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHONPATH
        value: backend
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: supersecretkey
      - key: ADMIN_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: MYSQL_PORT
        value: 3306
